# Generated by Django 5.1.5 on 2025-02-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_remove_faq_question_bn_remove_faq_question_gu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_bn_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_gu_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_hi_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_mr_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_ta_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_te_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_gu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_mr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_te',
            field=models.TextField(blank=True, null=True),
        ),
    ]
