# Generated by Django 5.1.5 on 2025-02-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_faq_is_bn_enabled_faq_is_gu_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='is_bn_enabled',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='is_gu_enabled',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='is_hi_enabled',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='is_mr_enabled',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='is_ta_enabled',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='is_te_enabled',
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_bn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_gu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_hi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_mr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_te',
            field=models.BooleanField(default=False),
        ),
    ]
