# Generated by Django 5.1.5 on 2025-02-01 20:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0008_remove_faq_question_en_remove_faq_question_gu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer_bn',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_hi',
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_gu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_mr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_te',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_bn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_hi',
            field=models.BooleanField(default=False),
        ),
    ]
