version: '3'

services:
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"  # Mapping host port 6380 to container port 6379
    networks:
      - app-network

  django:
    build: .
    container_name: django-container
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
